### ISSUE TITLE
Can't download traces easily

### ISSUE THREAD

**Issue by esprehn** [paulirish/trace.cafe#5]
You can't right click the trace viewer at all for some reason, and you can't choose "Save Profile..." to download the trace. I have to keep opening the dev tools on trace.cafe and then finding the resource load to download the trace itself.

**Comment by paulirish** [comment]
Heh. tbh I used to do some weird workaround like that too.. Then my colleague was like "why arent you using the Download icon?"

<img width="244" alt="image" src="https://github.com/paulirish/trace.cafe/assets/39191/7d1f8336-0e58-4611-91cb-e5f766813407">

And i'm like... 'theres no way that works'... But it does. :p

**Comment by esprehn** [comment]
Woah no way, I've never clicked those buttons before or realized what they did! It's still weird that right clicking is blocked, but I'm glad I don't need to do a hack to download it anymore. :P
